name: Build mysql-operator-python-deps container image
on:
  workflow_dispatch:
  push:
    branches: ['multiarch-build']
    paths: ['docker-deps/*']
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker context for buildx
        run: |
          docker context create buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/mysql-operator-python-deps
          tags: |
            type=raw,value=3.9.5
          labels: |
            org.opencontainers.image.title=mysql-operator-python-deps
            org.opencontainers.image.description=MySQL Operator for Kubernetes build dependency container image

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
    
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          endpoint: buildx
          platforms: linux/amd64,linux/arm64

      - name: Download python-3.9.5
        run: curl -L -o docker-deps/Python-3.9.5.tgz https://www.python.org/ftp/python/3.9.5/Python-3.9.5.tgz

      - name: Build python deps container
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PYTHON_TARBALL=Python-3.9.5.tgz
            PYTHON_BASE_DIR=/opt/python
            PYTHON_ROOT=Python-3.9.5
          context: docker-deps/.
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
